// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uber.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UberRoot

@interface UberRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - GetEstimatesPriceRequest

typedef GPB_ENUM(GetEstimatesPriceRequest_FieldNumber) {
  GetEstimatesPriceRequest_FieldNumber_EndLatitude = 1,
  GetEstimatesPriceRequest_FieldNumber_EndLongitude = 2,
  GetEstimatesPriceRequest_FieldNumber_StartLatitude = 3,
  GetEstimatesPriceRequest_FieldNumber_StartLongitude = 4,
};

@interface GetEstimatesPriceRequest : GPBMessage

@property(nonatomic, readwrite) double endLatitude;

@property(nonatomic, readwrite) double endLongitude;

@property(nonatomic, readwrite) double startLatitude;

@property(nonatomic, readwrite) double startLongitude;

@end

#pragma mark - GetEstimatesPriceResponse

typedef GPB_ENUM(GetEstimatesPriceResponse_FieldNumber) {
  GetEstimatesPriceResponse_FieldNumber_ItemsArray = 1,
};

@interface GetEstimatesPriceResponse : GPBMessage

// |itemsArray| contains |PriceEstimate|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *itemsArray;
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - GetEstimatesTimeRequest

typedef GPB_ENUM(GetEstimatesTimeRequest_FieldNumber) {
  GetEstimatesTimeRequest_FieldNumber_CustomerUuid = 1,
  GetEstimatesTimeRequest_FieldNumber_ProductId = 2,
  GetEstimatesTimeRequest_FieldNumber_StartLatitude = 3,
  GetEstimatesTimeRequest_FieldNumber_StartLongitude = 4,
};

@interface GetEstimatesTimeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *customerUuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productId;

@property(nonatomic, readwrite) double startLatitude;

@property(nonatomic, readwrite) double startLongitude;

@end

#pragma mark - GetEstimatesTimeResponse

typedef GPB_ENUM(GetEstimatesTimeResponse_FieldNumber) {
  GetEstimatesTimeResponse_FieldNumber_ItemsArray = 1,
};

@interface GetEstimatesTimeResponse : GPBMessage

// |itemsArray| contains |Product|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *itemsArray;
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - GetHistoryRequest

typedef GPB_ENUM(GetHistoryRequest_FieldNumber) {
  GetHistoryRequest_FieldNumber_Limit = 1,
  GetHistoryRequest_FieldNumber_Offset = 2,
};

@interface GetHistoryRequest : GPBMessage

@property(nonatomic, readwrite) int32_t limit;

@property(nonatomic, readwrite) int32_t offset;

@end

#pragma mark - GetProductsRequest

typedef GPB_ENUM(GetProductsRequest_FieldNumber) {
  GetProductsRequest_FieldNumber_Latitude = 1,
  GetProductsRequest_FieldNumber_Longitude = 2,
};

@interface GetProductsRequest : GPBMessage

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@end

#pragma mark - GetProductsResponse

typedef GPB_ENUM(GetProductsResponse_FieldNumber) {
  GetProductsResponse_FieldNumber_ItemsArray = 1,
};

@interface GetProductsResponse : GPBMessage

// |itemsArray| contains |Product|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *itemsArray;
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - Activities

typedef GPB_ENUM(Activities_FieldNumber) {
  Activities_FieldNumber_Count = 1,
  Activities_FieldNumber_HistoryArray = 2,
  Activities_FieldNumber_Limit = 3,
  Activities_FieldNumber_Offset = 4,
};

@interface Activities : GPBMessage

@property(nonatomic, readwrite) int32_t count;

// |historyArray| contains |Activity|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *historyArray;
@property(nonatomic, readonly) NSUInteger historyArray_Count;

@property(nonatomic, readwrite) int32_t limit;

@property(nonatomic, readwrite) int32_t offset;

@end

#pragma mark - Activity

typedef GPB_ENUM(Activity_FieldNumber) {
  Activity_FieldNumber_Uuid = 1,
};

@interface Activity : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - Error

typedef GPB_ENUM(Error_FieldNumber) {
  Error_FieldNumber_Code = 1,
  Error_FieldNumber_Fields = 2,
  Error_FieldNumber_Message = 3,
};

@interface Error : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fields;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - PriceEstimate

typedef GPB_ENUM(PriceEstimate_FieldNumber) {
  PriceEstimate_FieldNumber_CurrencyCode = 1,
  PriceEstimate_FieldNumber_DisplayName = 2,
  PriceEstimate_FieldNumber_Estimate = 3,
  PriceEstimate_FieldNumber_HighEstimate = 4,
  PriceEstimate_FieldNumber_LowEstimate = 5,
  PriceEstimate_FieldNumber_ProductId = 6,
  PriceEstimate_FieldNumber_SurgeMultiplier = 7,
};

@interface PriceEstimate : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *currencyCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *displayName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *estimate;

@property(nonatomic, readwrite) int32_t highEstimate;

@property(nonatomic, readwrite) int32_t lowEstimate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productId;

@property(nonatomic, readwrite) int32_t surgeMultiplier;

@end

#pragma mark - Product

typedef GPB_ENUM(Product_FieldNumber) {
  Product_FieldNumber_Capacity = 1,
  Product_FieldNumber_Description_p = 2,
  Product_FieldNumber_DisplayName = 3,
  Product_FieldNumber_Image = 4,
  Product_FieldNumber_ProductId = 5,
};

@interface Product : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *capacity;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *displayName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *image;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productId;

@end

#pragma mark - Profile

typedef GPB_ENUM(Profile_FieldNumber) {
  Profile_FieldNumber_Email = 1,
  Profile_FieldNumber_FirstName = 2,
  Profile_FieldNumber_LastName = 3,
  Profile_FieldNumber_Picture = 4,
  Profile_FieldNumber_PromoCode = 5,
};

@interface Profile : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *picture;

@property(nonatomic, readwrite, copy, null_resettable) NSString *promoCode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
