# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber.proto

require 'google/protobuf'

require 'google/protobuf/empty'
require 'google/api/annotations'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "uberapi.GetEstimatesPriceRequest" do
    optional :end_latitude, :double, 1
    optional :end_longitude, :double, 2
    optional :start_latitude, :double, 3
    optional :start_longitude, :double, 4
  end
  add_message "uberapi.GetEstimatesPriceResponse" do
    repeated :items, :message, 1, "uberapi.PriceEstimate"
  end
  add_message "uberapi.GetEstimatesTimeRequest" do
    optional :customer_uuid, :string, 1
    optional :product_id, :string, 2
    optional :start_latitude, :double, 3
    optional :start_longitude, :double, 4
  end
  add_message "uberapi.GetEstimatesTimeResponse" do
    repeated :items, :message, 1, "uberapi.Product"
  end
  add_message "uberapi.GetHistoryRequest" do
    optional :limit, :int32, 1
    optional :offset, :int32, 2
  end
  add_message "uberapi.GetProductsRequest" do
    optional :latitude, :double, 1
    optional :longitude, :double, 2
  end
  add_message "uberapi.GetProductsResponse" do
    repeated :items, :message, 1, "uberapi.Product"
  end
  add_message "uberapi.Activities" do
    optional :count, :int32, 1
    repeated :history, :message, 2, "uberapi.Activity"
    optional :limit, :int32, 3
    optional :offset, :int32, 4
  end
  add_message "uberapi.Activity" do
    optional :uuid, :string, 1
  end
  add_message "uberapi.Error" do
    optional :code, :int32, 1
    optional :fields, :string, 2
    optional :message, :string, 3
  end
  add_message "uberapi.PriceEstimate" do
    optional :currency_code, :string, 1
    optional :display_name, :string, 2
    optional :estimate, :string, 3
    optional :high_estimate, :int32, 4
    optional :low_estimate, :int32, 5
    optional :product_id, :string, 6
    optional :surge_multiplier, :int32, 7
  end
  add_message "uberapi.Product" do
    optional :capacity, :string, 1
    optional :description, :string, 2
    optional :display_name, :string, 3
    optional :image, :string, 4
    optional :product_id, :string, 5
  end
  add_message "uberapi.Profile" do
    optional :email, :string, 1
    optional :first_name, :string, 2
    optional :last_name, :string, 3
    optional :picture, :string, 4
    optional :promo_code, :string, 5
  end
end

module Uberapi
  GetEstimatesPriceRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.GetEstimatesPriceRequest").msgclass
  GetEstimatesPriceResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.GetEstimatesPriceResponse").msgclass
  GetEstimatesTimeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.GetEstimatesTimeRequest").msgclass
  GetEstimatesTimeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.GetEstimatesTimeResponse").msgclass
  GetHistoryRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.GetHistoryRequest").msgclass
  GetProductsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.GetProductsRequest").msgclass
  GetProductsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.GetProductsResponse").msgclass
  Activities = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.Activities").msgclass
  Activity = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.Activity").msgclass
  Error = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.Error").msgclass
  PriceEstimate = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.PriceEstimate").msgclass
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.Product").msgclass
  Profile = Google::Protobuf::DescriptorPool.generated_pool.lookup("uberapi.Profile").msgclass
end
